import Navbar from "./Navbar"
import Footer from "./Footer"
import Header from "./Header/Header"
import Input from "./Input"
import OAuthbtn from "./OAuthbtn"
import LeaderBoard from "./LeaderBoard"
import Modal from "./Modal"
import Button from "./Button"
import Select from "./Select"
export {Navbar, Footer, Header,Input ,OAuthbtn,LeaderBoard,Modal,Button,Select}